version: v2beta1
name: cncf-demo
pipelines:
  dev:
    run: |-
      ytt --file ytt/schema.yaml --file ytt/resources --data-values-file ytt/values-dev.yaml | tee yaml/dev/app.yaml
      create_deployments --all
      start_dev app
deployments:
  app:
    kubectl:
      manifests:
        - yaml/dev
dev:
  app:
    labelSelector:
      app.kubernetes.io/name: cncf-demo
    devImage: ghcr.io/loft-sh/devspace-containers/go:1.18-alpine
    sync:
      - path: ./
    terminal:
      command: ./devspace_start.sh
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    ports:
      - port: "8080"
    open:
      - url: http://localhost:8080
images:
  app:
    image: index.docker.io/thedeveloperpotato/cncf-demo
